stages:
  - test
  - build-and-push

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

test_build:
  stage: test
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
  script:
    - docker build -t test-build .
  rules:
    - if: $CI_COMMIT_BRANCH != "main"

publish_latest:
  stage: build-and-push
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"