stages:
  - test-build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

docker_build_test:
  stage: test-build
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
  script:
    - docker info
    - docker build -t novel-converter-test .
    - echo "Build test passed successfully!"