stages:
  - test
  - build-and-push

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

.docker_setup: &docker_setup
  image: docker:27
  services:
    - name: docker:27-dind
      alias: docker
      command: ["--insecure-registry", "registry.tigerhabitat.cc"]
  before_script:
    - until docker info >/dev/null 2>&1; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

test_build:
  <<: *docker_setup
  stage: test
  script:
    - docker build -t test-build .
  rules:
    - if: '$CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != "dev"'

publish_dev:
  <<: *docker_setup
  stage: build-and-push
  script:
    - docker build -t $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'

publish_latest:
  <<: *docker_setup
  stage: build-and-push
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'